// Code generated by "stringer -type=StdCode -linecomment"; DO NOT EDIT.

package faults

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[FatalError-1]
	_ = x[OperationFail-2]
}

const _StdCode_name = "UnknownFatal ErrorOperation Failed"

var _StdCode_index = [...]uint8{0, 7, 18, 34}

func (i StdCode) String() string {
	if i < 0 || i >= StdCode(len(_StdCode_index)-1) {
		return "StdCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StdCode_name[_StdCode_index[i]:_StdCode_index[i+1]]
}
